env: "local" # Type of environment (prod, local)

pgsql:
  host: ""
  port: ""
  user: ""
  password: ""
  dbname: ""

kafka:
  interval: 100
  brokers:
    - "localhost:9091"
    - "localhost:9092"
    - "localhost:9093"

parser:
  timeout: 5s
  interval: 10s
  worker:
    count: 5
    interval: 1s